const mongoose = require('mongoose');

const buddyNotificationSchema = new mongoose.Schema({
  groupId: { type: mongoose.Schema.Types.ObjectId, ref: 'StudyGroup', required: true },
  type: { 
    type: String, 
    enum: ['welcome', 'reminder', 'summary', 'suggestion', 'inactivity_alert'],
    required: true 
  },
  message: { type: String, required: true },
  metadata: { type: mongoose.Schema.Types.Mixed },
  isRead: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now }
});

const weeklySummarySchema = new mongoose.Schema({
  groupId: { type: mongoose.Schema.Types.ObjectId, ref: 'StudyGroup', required: true },
  weekStart: { type: Date, required: true },
  weekEnd: { type: Date, required: true },
  stats: {
    totalSessions: { type: Number, default: 0 },
    newMembers: { type: Number, default: 0 },
    newMaterials: { type: Number, default: 0 },
    activeMembers: { type: Number, default: 0 }
  },
  sentAt: { type: Date, default: Date.now }
});

const materialTagSchema = new mongoose.Schema({
  materialId: { type: mongoose.Schema.Types.ObjectId, ref: 'StudyMaterial', required: true },
  groupId: { type: mongoose.Schema.Types.ObjectId, ref: 'StudyGroup', required: true },
  tags: [{ type: String }],
  autoGenerated: { type: Boolean, default: true },
  createdAt: { type: Date, default: Date.now }
});

const BuddyNotification = mongoose.model('BuddyNotification', buddyNotificationSchema);
const WeeklySummary = mongoose.model('WeeklySummary', weeklySummarySchema);
const MaterialTag = mongoose.model('MaterialTag', materialTagSchema);

module.exports = { BuddyNotification, WeeklySummary, MaterialTag };